apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    component: frontend
spec:
  containers:
    - name: webapp-images
      image: 061188934096.dkr.ecr.us-east-1.amazonaws.com/application-repository:v0.1
      env:
        - name: DBPWD
          value: pass1234
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080